= convert-resources(1)
:doctype: manpage
:manmanual: Manual for convert-resources
:mansource: convert-resources
:revdate: 2025-03-08
:docdate: {revdate}

== NAME
convert-resources - convert resources to embed in GBA ROMs

== SYNOPSIS
*convert-resources* [*-h*] _FILE_...

== DESCRIPTION
Convert resources listed in the specified files into GBA-readable
formats for easy embedding into ROMs. Resources are converted into C
arrays of uncompressed data which can be compiled or included into other
code.

Each input _FILE_ must be a valid JSON or TOML file, respectively having
the '.json' and '.toml' extensions. These files can be used to list the
resources to convert. See FILE FORMAT for details.

=== Resource types
*tilesets*::
Images composed of tiles of a given size, converted into arrays of type
*u8* (unsigned 8-bit). Each tile is made up of 8x8 blocks. To match the
behavior of GBA hardware, the scanning order is: tiles, blocks, pixels.

*palettes*::
Images acting as lists of 16-bit colors, converted into arrays of type
*u16* (unsigned 16-bit). Pixels are scanned line by line.

*images*::
Generic images, converted into arrays of type *u8* (unsigned 8-bit) or
*u16* (unsigned 16-bit), depending on the bits-per-pixel property.
Pixels are scanned line by line.

*files*::
Generic files translated directly into arrays of type *u8* (unsigned
8-bit) without applying any conversion. These may contain text, raw
audio, level files...

=== Color mapping of images
Images converted to 4 or 8 bits-per-pixel are encoded using indexed
colors, that is, pixels are stored in memory as palette indexes. When
converting such images, one or more color-to-index lookup tables must be
defined.

For *tilesets*, all pixels within a tile are mapped using the same
lookup table. For *images*, all pixels of the entire image are mapped
using the same lookup table. In both cases, the lookup table used is the
first that contains all the colors inside the area.

A palette image, treated as a 1-dimensional array of colors, can be used
to supply the lookup tables. The palette is split into rows of 16 or 256
colors, for 4 or 8 bits-per-pixel, respectively. Each row defines a
lookup table: colors are mapped to their first position within the row.

Additional color mappings can be added to all lookup tables by listing
them in the *'colors'* property of images and tilesets. These mappings
take priority over the palette image. See below for details.

== FILE FORMAT
An input _FILE_ may contain global properties and lists of resources.
Lists of resources are named after the type of resource contained (e.g.,
'images', 'palettes'). Each entry is an object with various properties.

=== Global properties
Global properties affect all resources within the same list file.

*input_dir* - string (optional)::
Pathname of the base directory in which to search for input resources.

*output_dir* - string (optional)::
Pathname of the base directory in which to place output files.

=== Common properties
*name* - string::
Name of the resource, used to name the generated array.

*input* - string::
Pathname of the resource file to convert, relative to either the
'input_dir' global property (if set) or the working directory.

*output* - string::
Pathname of the output file to generate, relative to either the
'output_dir' global property (if set) or the working directory.

*static* - boolean (optional)::
Whether the generated array should have the *static* modifier or not.
Defaults to *false*.

=== Tilesets properties
*tile_size* - integer _or_ list::
How many horizontal and vertical blocks make up a tile of the tileset.
This property can either be a list of two integers (width and height) or
a single integer if width and height are the same.

*bpp* - integer::
Bits-per-pixel (or color depth) of the tileset. Allowed values are *4*
and *8*.

*palette* - string (optional)::
Pathname of the palette used to map colors to their index, relative to
the working directory (not affected by 'input_dir').

*colors* - object (optional)::
Table of color-to-index mappings in the form *"COLOR": INDEX*. The
24-bit RGB color must be written in hexadecimal, with an optional '#'
character at the beginning (e.g., #ff00ff), while the index must be an
integer. Color mappings specified here take priority over the palette.

=== Images properties
*bpp* - integer::
Bits-per-pixel (or color depth) of the image. Allowed values are *8* and
*16*.

*palette* - string (optional)::
Same as the property for tilesets: see above.

*colors* - object (optional)::
Same as the property for tilesets: see above.

== EXAMPLES
*convert-resources* _res/resources.json_::
Read _res/resources.json_ and convert resources listed in that file.

*convert-resources* _a.json_ _b.toml_::
Read both _a.json_ and _b.toml_ and convert resources listed in those
two files.

=== Examples of list file
*example.json*::
[source,json]
----
{
    "input_dir": "res",
    "output_dir": "src/res",

    "tilesets": [
        {
            "name": "tileset",
            "input": "img/tileset.png",
            "output": "tileset.c",
            "static": true,

            "tile_size": [ 2, 2 ],
            "palette": "res/img/palette.png",
            "colors": {
                "#ff00ff": 0,
                "#000000": 15
            },
            "bpp": 4
        }
    ],
    "palettes": [
        {
            "name": "palette",
            "input": "img/palette.png",
            "output": "palette.c"
        }
    ]
}
----

*example.toml*
[source,toml]
----
input_dir  = 'res'
output_dir = 'src/res'

[[images]]
    name   = 'background'
    input  = 'img/background.png'
    output = 'img/background.c'
    static = true

    bpp = 16

[[files]]
    name   = 'music_track_1'
    input  = 'music/track-1.raw'
    output = 'music/track-1.c'

[[files]]
    name   = 'music_track_2'
    input  = 'music/track-2.raw'
    output = 'music/track-2.c'
----

== AUTHORS
*convert-resources* was written by Vulcalien <\vulcalien@vulcalien.net>.
