input_dir  = 'res'
output_dir = 'src/res'

[[images]]
    name = 'background'

    input  = 'img/background.png'
    output = 'img/background.c'

    bpp = 16

    static = true

[[files]]
    name = 'music_track_1'

    input  = 'music/track-1.raw'
    output = 'music/track-1.c'

[[files]]
    name = 'music_track_2'

    input  = 'music/track-2.raw'
    output = 'music/track-2.c'
